name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main # Adjust this to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        run: |
          # Your deployment commands here
          echo "Deploying branch $BRANCH_NAME"
